"""
Django settings for watchcase_tracker project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gjye57-rx)^o3)f$ix_jy#802*56@oljtx1zrpo6_$-hzvb#mv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "192.168.1.2",
    "localhost",
    "127.0.0.1",
    ".devtunnels.ms",
]

# Required for Django 4.0+ CSRF Origin validation.
# Extend this list with production hostname/IP when deploying.
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'http://127.0.0.1',
    'http://localhost',
]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'csp',
    
    # ownapps
    'modelmasterapp',
    'adminportal',
    'DayPlanning',
    'InputScreening',
    'Brass_QC',
    'BrassAudit',
    'IQF',
    'Jig_Loading',
    'Jig_Unloading',
    'JigUnloading_Zone2',
    'Inprocess_Inspection',
    'Nickel_Inspection',
    'nickel_inspection_zone_two',
    'Nickel_Audit',
    'nickel_audit_zone_two',
    'Recovery_DP',
    'Recovery_IS',
    'Recovery_Brass_QC',
    'Recovery_BrassAudit',
    'Recovery_IQF',
    'ReportsModule',
    'SpiderSpindle_Z1',
    'SpiderSpindle_Z2',
    'social_django',
]

# Add custom backend (keep default ModelBackend as fallback)
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Ensure social login redirects to the dashboard
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/home/'
SOCIAL_AUTH_LOGIN_ERROR_URL = '/accounts/login/'
SOCIAL_AUTH_LOGIN_URL = '/accounts/login/'

# social-auth pipeline: include our linker function
SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'watchcase_tracker.sso_pipeline.link_sso_by_email_or_username',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'adminportal.middleware.CSPMiddleware',
    'adminportal.middleware.LoginLatencyMiddleware',
    'middleware.forbidden_redirect.ForbiddenToLoginMiddleware',
    'watchcase_tracker.middleware.latency_middleware.LatencyMiddleware',
]

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/home/'
LOGOUT_REDIRECT_URL = '/accounts/login/'
AUTH_LOGIN_TEMPLATE = 'login.html'

ROOT_URLCONF = 'watchcase_tracker.urls'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'static/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
                'watchcase_tracker.context_processors.csp_nonce',
                'adminportal.context_processors.user_permissions',
            ],
        },
    },
]

WSGI_APPLICATION = 'watchcase_tracker.wsgi.application'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
}

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'watchcase2026',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

PASSWORD_HASHERS = [
    'watchcase_tracker.hashers.TTTFastPBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]

# Cache backend — in-process per worker.
# To share across Gunicorn workers (recommended for production scale-out),
# replace with a Redis backend:
#   pip install django-redis
#   CACHES = {'default': {'BACKEND': 'django_redis.cache.RedisCache',
#                         'LOCATION': 'redis://127.0.0.1:6379/1'}}
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'ttt-default',
        'TIMEOUT': 300,
        'OPTIONS': {
            'MAX_ENTRIES': 2000,
        },
    }
}

# cached_db reads the session from the in-process cache on warm hits,
# falling back to PostgreSQL only on a miss. This removes one DB round-trip
# from every authenticated request compared to the plain 'db' backend.
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
SESSION_SAVE_EVERY_REQUEST = False
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_AGE = 86400  # 24 hours

ENABLE_MICROSOFT_LOGIN = False
ENABLE_LOGIN_LATENCY_LOGS = False
ENABLE_DASHBOARD_LATENCY_LOGS = False

# Internationalization
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True

# Static files
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Minimal logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'django.server': {
            '()': 'django.utils.log.ServerFormatter',
            'format': '[{server_time}] {message}',
            'style': '{',
            'datefmt': '%d/%b/%Y %I:%M:%S %p',
        },
    },
    'handlers': {
        'django.server': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'django.server',
        },
    },
    'loggers': {
        'django.server': {
            'handlers': ['django.server'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Microsoft (Entra ID) / MSAL settings
MSAL_CLIENT_ID = "54a2fd19-0009-4e29-9d7b-b33e9ae8fbfa"
MSAL_CLIENT_SECRET = os.getenv("MSAL_CLIENT_SECRET")
MSAL_TENANT_ID = "common"
MSAL_REDIRECT_PATH = "/auth/microsoft/callback/"
MSAL_SCOPES = ["User.Read"]